<div class="footer">
    <div class="cr w1000 center">
        <p>
            Copyright©2010- <?php echo @D($date,'2015-6-26');?>  <a href='http://www.baidu.com/'>www.baidu.com</a>  All Rights Reserved &nbsp;&nbsp;联系邮箱:188818520@qq.com</p>
        <p>牛牛金融平台技术由重庆亿与科技有限公司开发维护&nbsp;ICP证：<a rel="nofollow" href='www.baidu.com' > <?php echo C('ICP','abcdefg'); ?></a></p>
        <p style="margin-top:10px;">
            <img width="121" height="47" src="http://source.baibeila.com/news/images/zzrz01.jpg" alt="中国互联网协会">
            <a rel="nofollow" href="http://net.china.cn/chinese/index.htm" target="_blank"><img width="121" height="47" src="http://source.baibeila.com/news/images/zzrz03.jpg" alt="不良信息举报中心"> </a>
            <a href="http://www.cqnet110.gov.cn" target="_blank" rel="nofollow"><img src="http://source.baibeila.com/news/images/wangjing.gif" width="121" height="47"></a>
        </p>
    </div>
</div>
</div>
<script type="text/javascript">
    var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
    document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F18ff923bda5c74bcb9a24a36d66c0cfe' type='text/javascript'%3E%3C/script%3E"));
</script>
</body>
</html>