<!DOCTYPE html>
<html>
<head>
    <title><?php  echo $title; ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" href="public/img/images/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="public/css/header-top-min.css"/>
    <script src="public/js/jquery-1.9.1.min.js"></script>


    <link rel="stylesheet" href="public/css/base.css"/>


</head>
<style>
    .col-main {
        width: 980px;
        /*white-space: nowrap;*/
    }

    #main-profile span {
        display: block;
        height: 35px;
        line-height: 35px;
    }

    table tr td {
        line-height: 35px;
        padding-left: 10px;
    }
</style>
<body>
<div class="wrap_top">
    <div class="top">
        <div class="top_nav">
            <a href="" title="首页">亿与科技</a>
        </div>
        <ul class="fr top_right">
            <li><a href="" class="savezm">保存到桌面</a></li>
            <li><a href="" class="scblx">收藏百里奚</a></li>
            <li><a href="" class="indexpage">百里奚搜索</a></li>
        </ul>
    </div>
</div>

<div id="logozone">
    <div class="logobox">
        <div class='rightzone'>
            <p style="margin-top:23px;">
                <a href='' class='emsbox' title="我的信箱">&nbsp;()&nbsp;信箱
                </a>
                <a href='' class='moneybox'>
                    钱包:&nbsp;&nbsp;
                </a>
                <a href='' class='moneybox' title="点击进入积分兑换中心">
                    积分:&nbsp;22点
                </a>
                <a href='' title="退出登录" class='logoutbox'>
                    退出
                </a>
            </p>
        </div>
        <div class='logo1'>
            <a href=''><img src='public/img/header.jpg' border='0' style="width: 50px"></a>
        </div>
    </div>
</div>
